#./run_one_benchmark.sh lbm _8MB_STTRAM LBM_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/lbm/lru8MB_Hybrid_1_Block/lbm_check.txt
#./run_one_benchmark.sh gcc _8MB_STTRAM GCC_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gcc/lru_8MB_Intraset_Swapping/gcc_check.txt
#./run_one_benchmark.sh astar _8MB_STTRAM ASTAR_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/astar/lru_8MB_Intraset_Swapping/astar_check.txt
#./run_one_benchmark.sh bwaves _8MB_STTRAM BWAVES_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/bwaves/lru_8MB_Intraset_Swapping/bwaves_check.txt
#./run_one_benchmark.sh bzip _8MB_STTRAM BZIP_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/bzip/lru_8MB_Intraset_Swapping/bzip_check.txt
#./run_one_benchmark.sh cactusADM _8MB_STTRAM CACTUSADM_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/cactusADM/lru_8MB_Intraset_Swapping/cactusADM_check.txt
#./run_one_benchmark.sh GemsFDTD _8MB_STTRAM GEMSFDTD_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/GemsFDTD/lru_8MB_Intraset_Swapping/GemsFDTD_check.txt
#./run_one_benchmark.sh gobmk _8MB_STTRAM GOBMK_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gobmk/lru_8MB_Intraset_Swapping/gobmk_check.txt
#./run_one_benchmark.sh gromacs _8MB_STTRAM GROMACS_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gromacs/lru_8MB_Intraset_Swapping/gromacs_check.txt
#./run_one_benchmark.sh h264ref _8MB_STTRAM H264REF_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/h264ref/lru_8MB_Intraset_Swapping/h264ref_check.txt
#./run_one_benchmark.sh hmmer _8MB_STTRAM HMMER_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/hmmer/lru_8MB_Intraset_Swapping/hmmer_check.txt
#./run_one_benchmark.sh leslie _8MB_STTRAM LESLIE_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/leslie/lru_8MB_Intraset_Swapping/leslie_check.txt
#./run_one_benchmark.sh libq _8MB_STTRAM LIBQ_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/libq/lru_8MB_Intraset_Swapping/libq_check.txt
#./run_one_benchmark.sh mcf _8MB_STTRAM MCF_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/mcf/lru_8MB_Intraset_Swapping/mcf_check.txt
./run_one_benchmark.sh milc _8MB_STTRAM MILC_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/milc/lru_8MB_Intraset_Swapping/milc_chec.txt
./run_one_benchmark.sh namd _8MB_STTRAM NAMD_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/namd/lru_8MB_Intraset_Swapping/namd_check.txt
./run_one_benchmark.sh omnetpp _8MB_STTRAM OMNETPP_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/omnetpp/lru_8MB_Intraset_Swapping/omnetpp_check.txt
./run_one_benchmark.sh perlbench _8MB_STTRAM PERLBENCH_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/perlbench/lru_8MB_Intraset_Swapping/perlbench_check.txt
./run_one_benchmark.sh sjeng _8MB_STTRAM SJENG_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/sjeng/lru_8MB_Intraset_Swapping/sjeng_check.txt
./run_one_benchmark.sh soplex _8MB_STTRAM SOPLEX_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/soplex/lru_8MB_Intraset_Swapping/soplex_check.txt
./run_one_benchmark.sh sphinx _8MB_STTRAM SPHINX_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/sphinx/lru_8MB_Intraset_Swapping/sphinx_check.txt
./run_one_benchmark.sh tonto _8MB_STTRAM TONTO_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/tonto/lru_8MB_Intraset_Swapping/tonto_check.txt
./run_one_benchmark.sh wrf _8MB_STTRAM WRF_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/wrf/lru_8MB_Intraset_Swapping/wrf_check.txt
./run_one_benchmark.sh zeusmp _8MB_STTRAM ZEUSMP_LRU_8MB_Intraset_Swapping 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/zeusmp/lru_8MB_Intraset_Swapping/zeusmp_check.txt

