./run_one_benchmark.sh lbm _8MB_STTRAM LBM_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/lbm/lru_30_5/lbm_check.txt
./run_one_benchmark.sh gcc _8MB_STTRAM GCC_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gcc/lru_30_5/gcc_check.txt
./run_one_benchmark.sh astar _8MB_STTRAM ASTAR_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/astar/lru_30_5/astar_check.txt
./run_one_benchmark.sh bwaves _8MB_STTRAM BWAVES_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/bwaves/lru_30_5/bwaves_check.txt
./run_one_benchmark.sh bzip _11 BZIP_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/bzip/lru_30_5/bzip_check.txt
./run_one_benchmark.sh cactusADM _11 CACTUSADM_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/cactusADM/lru_30_5/cactusADM_check.txt
./run_one_benchmark.sh GemsFDTD _8MB_STTRAM GEMSFDTD_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/GemsFDTD/lru_30_5/GemsFDTD_check.txt
./run_one_benchmark.sh gobmk _8MB_STTRAM GOBMK_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gobmk/lru_30_5/gobmk_check.txt
./run_one_benchmark.sh gromacs _8MB_STTRAM GROMACS_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/gromacs/lru_30_5/gromacs_check.txt
./run_one_benchmark.sh h264ref _8MB_STTRAM H264REF_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/h264ref/lru_30_5/h264ref_check.txt
./run_one_benchmark.sh hmmer _8MB_STTRAM HMMER_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/hmmer/lru_30_5/hmmer_check.txt
./run_one_benchmark.sh leslie _8MB_STTRAM LESLIE_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/leslie/lru_30_5/leslie_check.txt
./run_one_benchmark.sh libq _8MB_STTRAM LIBQ_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/libq/lru_30_5/libq_check.txt
./run_one_benchmark.sh mcf _8MB_STTRAM MCF_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/mcf/lru_30_5/mcf_check.txt
./run_one_benchmark.sh milc _8MB_STTRAM MILC_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/milc/lru_30_5/milc_check.txt
./run_one_benchmark.sh namd _8MB_STTRAM NAMD_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/namd/lru_30_5/namd_check.txt
./run_one_benchmark.sh omnetpp _8MB_STTRAM OMNETPP_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/omnetpp/lru_30_5/omnetpp_check.txt
./run_one_benchmark.sh perlbench _8MB_STTRAM PERLBENCH_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/perlbench/lru_30_5/perlbench_check.txt
./run_one_benchmark.sh sjeng _8MB_STTRAM SJENG_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/sjeng/lru_30_5/sjeng_check.txt
./run_one_benchmark.sh soplex _8MB_STTRAM SOPLEX_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/soplex/lru_30_5/soplex_check.txt
./run_one_benchmark.sh sphinx _8MB_STTRAM SPHINX_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/sphinx/lru_30_5/sphinx_check.txt
./run_one_benchmark.sh tonto _8MB_STTRAM TONTO_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/tonto/lru_30_5/tonto_check.txt
./run_one_benchmark.sh wrf _8MB_STTRAM WRF_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/wrf/lru_30_5/wrf_check.txt
./run_one_benchmark.sh zeusmp _8MB_STTRAM ZEUSMP_8MB_Write_Access_Pattern_Correct 2>&1 | tee /home/ishita/Desktop/Sniper/sniper-7.2/lap_lru_results/zeusmp/lru_30_5/zeusmp_check.txt

